name: Release

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Configure tag
        shell: bash
        run: |
          latest_tag=${{ github.ref_name }}
          echo "IMAGE_TAG=${latest_tag}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build . --file examples/Dockerfile -t greptime/greptimeai-langchain-example:${{ env.IMAGE_TAG }}
          docker push greptime/greptimeai-langchain-example:${{ env.IMAGE_TAG }}
